# Generated by Django 4.2.6 on 2023-11-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArteNativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_NombreCliente', to='ArteNativo.clientes'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_NombreProducto', to='ArteNativo.productos'),
        ),
    ]
